//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
namespace Bank {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public class BankQuoteRequest {
        
        /// <remarks/>
        public int SSN;
        
        /// <remarks/>
        public int CreditScore;
        
        /// <remarks/>
        public int HistoryLength;
        
        /// <remarks/>
        public int LoanAmount;
        
        /// <remarks/>
        public int LoanTerm;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public class BankQuoteReply {
        
        /// <remarks/>
        public System.Double InterestRate;
        
        /// <remarks/>
        public string QuoteID;
        
        /// <remarks/>
        public int ErrorCode;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public class Run {
    }
}
