//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementConsole.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManagementConsole.Configuration.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;clients&gt;
        ///  &lt;client id=&quot;92022db8-750a-4481-afc7-dc2dcfb8fc20\\1&quot; name=&quot;Test&quot; description=&quot;&quot;&gt;
        ///    &lt;group id=&quot;&quot;&gt;
        ///      &lt;config id=&quot;&quot; name=&quot;mode&quot; value=&quot;loanbroker&quot; /&gt;
        ///      &lt;config id=&quot;&quot; name=&quot;requestQueue&quot; value=&quot;loanRequestQueue&quot; /&gt;
        ///      &lt;config id=&quot;&quot; name=&quot;replyQueue&quot; value=&quot;loanReplyQueue&quot; /&gt;
        ///      &lt;config id=&quot;&quot; name=&quot;numMessages&quot; value=&quot;50&quot; /&gt;
        ///    &lt;/group&gt;
        ///  &lt;/client&gt;
        ///  &lt;client id=&quot;&quot; name=&quot;&quot; description=&quot;&quot;&gt;
        ///    &lt;group id=&quot;&quot;&gt;
        ///      &lt;config id=&quot;&quot; name=&quot;&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClientConfigurations {
            get {
                return ResourceManager.GetString("ClientConfigurations", resourceCulture);
            }
        }
    }
}
